# Import NumPy Library

In [2]:
import numpy as np

In [3]:
np.__version__

'1.21.5'

# Creating Array

In [4]:
#Fungsi array 
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
#Fungsi Zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
#Fungsi one 
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
#Fungsi Empty 
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
#Fungsi Arange 
np.arange(4)

array([0, 1, 2, 3])

In [10]:
#Fungsi arange dengan interval/step
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
#Fungsi Append 
arr = np.arange(1,9)
print(arr)
np.append(arr,[1,2])

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [13]:
#Fungsi Delete 
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [26]:
#Fungsi Sort 
arr = np.array([[2,1,5,3,7,4,6,8],[1,2,3,4,5,6,7,8]])
print(arr)
print(np.sort(arr))

[[2 1 5 3 7 4 6 8]
 [1 2 3 4 5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [27]:
#Mencari Dimensi Array
arr.ndim

2

In [28]:
#Ukuran Array
arr.size

16

In [29]:
#Shape dari Array 
arr.shape

(2, 8)

In [31]:
# Contoh lain
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [32]:
array_example.ndim

3

In [33]:
array_example.size

24

In [34]:
array_example.shape

(3, 2, 4)

# Reshape Array

In [35]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [36]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
# Convert 1D to 2D
a = np.arange(1,7)
a.shape

(6,)

In [39]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [41]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [42]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [45]:
b =  np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [46]:
c =  np.expand_dims(a, axis = 0)
c.shape

(1, 6)

# Indexing and Slicing

In [47]:
#Slicing
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [48]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
condition = (a >= 5)
print(a[condition])

[ 5  6  7  8  9 10 11 12]


In [52]:
condition_2 = a[a%2==0]
print(condition_2)

[ 2  4  6  8 10 12]


In [53]:
#Dua kondisi berbeda 
c = a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [54]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [58]:
#Vertical stack 
a1 = np.array([
    [1,1],
    [2,2]
])

a2 = np.array([
    [3,3],
    [4,4]
])

np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [59]:
#Horizontal stack 
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [60]:
#Split Array 
arr = np.arange(1,25)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [61]:
#Split Array
np.hsplit(arr, 2)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [62]:
a = np.array([
    [1,2,3,4], 
    [5,6,7,8],
    [9,10,11,12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [65]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [67]:
a.sum()

10

In [68]:
b = np.array([[1,1], [2,2]])
b.sum()

6

In [69]:
#Sum by Columns 
b.sum(axis=1)

array([2, 4])

In [70]:
#Sum by ROw 
b.sum(axis=0)

array([3, 3])

In [71]:
data = np.array([1,2])
data

array([1, 2])

In [72]:
ones = np.ones(2)
ones

array([1., 1.])

In [73]:
data + ones

array([2., 3.])

In [74]:
data * ones

array([1., 2.])

In [75]:
data / ones

array([1., 2.])

In [76]:
data - ones

array([0., 1.])

# Broadcasting

In [77]:
data*1.6

array([1.6, 3.2])

# More Array Operations

In [78]:
data.max()

2

In [79]:
data

array([1, 2])

In [80]:
data.min()

1

In [81]:
data.sum()

3

# Matrices 

In [84]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [85]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
np.random.random((3,2))

array([[0.55729464, 0.55575183],
       [0.67707374, 0.51480755],
       [0.86961609, 0.64650842]])

In [88]:
data = np.array([
    [1,2],
    [3,4]
])
data 

array([[1, 2],
       [3, 4]])

In [89]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [90]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [91]:
one_row = np.ones((1,2))

In [92]:
one_row

array([[1., 1.]])

In [93]:
data + one_row

array([[2., 3.],
       [4., 5.]])

# Dot Product

In [94]:
a1 = np.array([[1,2,3], [4,5,6]])
a1.shape

(2, 3)

In [95]:
a2 = np.array([[7,8], [9,10], [11, 12]])
a2.shape

(3, 2)

In [96]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [97]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
data[0]

array([1, 2])

In [99]:
data[1]

array([3, 4])

In [102]:
data[0][1] == data[0,1]

True

In [103]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [104]:
data[0:2, 1]

array([2, 4])

## Matrix Aggregation

In [105]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
data.max()

6

In [107]:
data.min()

1

In [108]:
data.sum()

21

In [109]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transpose and Reshape Matrix

In [110]:
data 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [120]:
data_col = np.arange(1,7)
data_col = np.array([data_col])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [121]:
data_col.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [122]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# N-Dimensional Array

In [124]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [125]:
ndarr.shape

(2, 2, 2)

In [128]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [130]:
np.random.random((4,3,2))

array([[[0.74802638, 0.8456441 ],
        [0.86563498, 0.98201858],
        [0.5809378 , 0.8689246 ]],

       [[0.77340785, 0.66788322],
        [0.92913715, 0.63019842],
        [0.27399462, 0.0549254 ]],

       [[0.49035026, 0.68166409],
        [0.05317211, 0.13488819],
        [0.59644137, 0.80760584]],

       [[0.03885969, 0.73379076],
        [0.85798299, 0.33037647],
        [0.68395404, 0.13274913]]])

# Flatten N-Dimensional Array

In [132]:
arrflat = np.array([
    [1,2,3,4], 
    [5,6,7,8], 
    [9,10,11,12]
])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
#Flatten to 1D Array 
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])